Name:           ros-kinetic-abseil-cpp
Version:        0.2.2
Release:        0%{?dist}
Summary:        ROS abseil_cpp package

Group:          Development/Libraries
License:        Apache
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  ros-kinetic-catkin
BuildRequires:  rsync

%description
The abseil_cpp package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Wed Nov 15 2017 dfaconti <davide.faconti@gmail.com> - 0.2.2-0
- Autogenerated by Bloom

* Tue Nov 14 2017 dfaconti <davide.faconti@gmail.com> - 0.2.1-0
- Autogenerated by Bloom

* Sat Oct 14 2017 dfaconti <davide.faconti@gmail.com> - 0.2.0-0
- Autogenerated by Bloom

* Fri Oct 13 2017 dfaconti <davide.faconti@gmail.com> - 0.1.4-0
- Autogenerated by Bloom

* Wed Oct 04 2017 dfaconti <davide.faconti@gmail.com> - 0.1.2-0
- Autogenerated by Bloom

* Sun Oct 01 2017 dfaconti <davide.faconti@gmail.com> - 0.1.1-0
- Autogenerated by Bloom

