Name:           ros-melodic-abseil-cpp
Version:        0.4.0
Release:        1%{?dist}
Summary:        ROS abseil_cpp package

Group:          Development/Libraries
License:        Apache
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  ros-melodic-catkin
BuildRequires:  rsync

%description
The abseil_cpp package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Tue May 28 2019 dfaconti <davide.faconti@gmail.com> - 0.4.0-1
- Autogenerated by Bloom

* Thu Jul 19 2018 dfaconti <davide.faconti@gmail.com> - 0.2.3-1
- Autogenerated by Bloom

* Thu Jul 19 2018 dfaconti <davide.faconti@gmail.com> - 0.2.3-0
- Autogenerated by Bloom

